### ISSUE TITLE
Per-overlord LotV Ventral Sacs not supported

### ISSUE THREAD

**Issue by jnwatson** [andrew-j-armstrong/SCFusion#8]
Sometime in the beta, they switched the Ventral Sacs overlord to be a per-overlord mutation that costs 25/25 and takes 12s.  It requires an evolution chamber.

**Comment by rufinq** [comment]
I have a fix.
1. Add this file in the "Versions" folder.
2. replace the prefix from "txt" to "xml". (I could not upload the xml file because Github refuses xml files)
[LotV_2_5_1_BU_20151023 (Overlord VC).txt](https://github.com/Carbon-12/SCFusion/files/558452/LotV_2_5_1_BU_20151023.Overlord.VC.txt)
